fix gzip compression
we need to register the deflate middleware
in the root app already, otherwise we get strange, such as:
(NoMethodError) "undefined method `empty?' for #<Rack::Deflater::GzipStream:0xXXXXXX>"